spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 261106017309-k65ui7lugcsiaihp92rk93cn3pdvq3sn.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email