name: official-gsm-admin-server-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

permissions: read-all

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up JDK 11 job has success
        if: ${{ success() }}
        run: echo "set-up JDK 11 is succeeded"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name : Setup Gradls's permission
        run : chmod +x gradlew 

      - name: Build with Gradle
        run : ./gradlew clean build --exclude-task test
        
      - name: official-gsm-admin-server-ci-success
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: 👍 official-gsm-admin-server-ci-success
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: official-gsm-admin-server-ci-failed
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: 👎 official-gsm-admin-server-ci-failed
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000
