name: official-gsm-admin-server-ci

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up JDK 11 job has success
        if: ${{ success() }}
        run: echo "set-up JDK 11 is succeeded"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name : Setup Gradls's permission
        run : chmod +x gradlew

      - name : make yml file
        run : touch ./src/main/resources/application.yml
          
          echo "${{ secrets.YML }}" > ./src/main/resources/application.yml
          
          touch ./src/main/resources/application-oauth.yml
          
          echo "${{ secrets.OAUTH_YML }}" > ./src/main/resources/application-oauth.yml

        shell: bash

      - name: Build with Gradle
        run : ./gradlew clean build --exclude-task test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t official-test-server .
          docker tag official-test-server ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/official-test-server:admin
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/official-test-server:admin

      - name: official-gsm-admin-server-ci-success
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: 👍 official-gsm-admin-server-ci-success
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: official-gsm-admin-server-ci-failed
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: 👎 official-gsm-admin-server-ci-failed
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000